version: "3.8"

services:
  proxy:
    extends:
      file: docker-compose.yml
      service: proxy
    image: ghcr.io/jisensee/adalia.info/proxy:latest

  mongodb:
    extends:
      file: docker-compose.yml
      service: mongodb

  server:
    extends:
      file: docker-compose.yml
      service: server
    image: ghcr.io/jisensee/adalia.info/server:latest

  client:
    extends:
      file: docker-compose.yml
      service: client
    image: ghcr.io/jisensee/adalia.info/client:latest

volumes:
  mongodb_data:
