name: build-prod
on:
  push:
    branches:
      - main
jobs:
  build-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: "Cache docker layers"
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{runner.os}}-buildx-${{github.sha}}
          restore-keys: |
            ${{runner.os}}-buildx-
      - name: Login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Proxy build and push
        uses: docker/build-push-action@v2
        with:
          context: proxy
          push: true
          tags: ghcr.io/${{github.repository_owner}}/adalia.info/proxy
      - name: Server build and push
        uses: docker/build-push-action@v2
        with:
          context: server
          push: true
          tags: ghcr.io/${{github.repository_owner}}/adalia.info/server
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Client build and push
        uses: docker/build-push-action@v2
        with:
          context: client
          push: true
          tags: ghcr.io/${{github.repository_owner}}/adalia.info/client
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
