name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
      -
        name: Proxy build and push
        uses: docker/build-push-action@v2
        with:
          context: proxy
          push: true
          tags: ghcr.io/${{github.repository_owner}}/adalia.info/proxy
      -
        name: Server build and push
        uses: docker/build-push-action@v2
        with:
          context: server
          push: true
          tags: ghcr.io/${{github.repository_owner}}/adalia.info/server
      -
        name: Client build and push
        uses: docker/build-push-action@v2
        with:
          context: client
          push: true
          tags: ghcr.io/${{github.repository_owner}}/adalia.info/client
