name: Client prod build
on:
  push:
    tags:
      - '*'
jobs:
  build-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Write app version
        run: >
          echo '{"version": "${{ env.RELEASE_VERSION }}"}' > ./client/version.json
      - name: Login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: client
          push: true
          tags: ghcr.io/${{github.repository_owner}}/adalia.info/client
          cache-from: type=gha
          cache-to: type=gha,mode=max
