name: Test server PR

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'server/**'

jobs:
  build-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
          cache: npm
          cache-dependency-path: server/package-lock.json
      - run: npm install
      - run: npm run codegen
      - run: npm run build
